LABEL EmuELEC
  LINUX /KERNEL
  FDT /rg32tw3ka.dtb
  APPEND boot=UUID=2701-5727 disk=UUID=e2b50327-8204-4d31-acb3-fde30421e72e quiet console=ttyFIQ0 console=tty0 net.iframes=0 fbcon=rotate:3 ssh consoleblank=0
